# Generated by Django 5.2.4 on 2025-07-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
